version: 2.1

jobs:
  build:
     machine:
      image: ubuntu-1604:202007-01
     steps:
        - checkout && git --version
        - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        - run: docker build . -t aayushsomani/lms:$SERVICE_NAME
        - run: docker push aayushsomani/lms:$SERVICE_NAME
  deploy:
     machine:
      image: ubuntu-1604:202007-01
     steps:
        - checkout
        - run: echo $ID_RSA | base64 -d > id_rsa && chmod 400 id_rsa
        - run: ssh -i id_rsa root@$VM_IP "IMAGE=aayushsomani/lms:$SERVICE_NAME bash -s" < deploy.sh  


workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:   
          requires:
            - build      
          filters:
            branches:
              only: master 
      
