version: 2.1

jobs:
  build:
     docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
     steps:
        - checkout
        - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        - run: docker build . -t aayushsomani/lms:$SERVICE_NAME
        - run: docker push aayushsomani/lms:$SERVICE_NAME
  deploy:
     docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
     steps:
        - checkout
        - run: echo $ID_RSA | base64 -d > id_rsa && chmod 400 id_rsa
        - run: ssh -i id_rsa root@$VM_IP "IMAGE=aayushsomani/lms:$SERVICE_NAME bash -s" < deploy.sh  


workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:        
          filters:
            branches:
              only: master 
      
